#!/usr/bin/env python3
"""Regenerate ``examples/crm/cassette.json`` from the deterministic mock provider.

Run from the repository root::

    python examples/crm/make_cassette.py

The cassette records exactly the grid the README's demo command replays. Change the
command and you must re-record: entries are keyed by a hash of the full request, so a
different ``--repeats``, ``--seed`` or ``--factors`` produces keys that are not in the
file, and the cassette provider raises rather than quietly falling back to a live call.

The output is labelled ``_provenance: synthetic`` because it is generated by a mock, not
captured from a model. Nothing in this repository presents generated output as a
measurement.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from toolsweep.adapters import load_file as load_catalogue  # noqa: E402
from toolsweep.providers import MockConfig, MockProvider, Request, write_cassette  # noqa: E402
from toolsweep.runner import SweepConfig, build_arms  # noqa: E402
from toolsweep.suite import load_file as load_suite  # noqa: E402

HERE = Path(__file__).resolve().parent

# Must match the README's cassette command exactly. Deliberately narrower than the
# headline `--factors all` sweep: a full-grid cassette at five repeats is 2,800 entries
# and 1.2 MB, which is not a reasonable thing to put in a git repository for a demo that
# the mock provider already reproduces offline for free.
FACTORS = ("naming.synonyms,description.negative",)
REPEATS = 3
SEED = 7


def main() -> int:
    catalogue, _ = load_catalogue(HERE / "catalogue.json")
    suite = load_suite(HERE / "suite.jsonl")

    provider = MockProvider(
        config=MockConfig(seed=SEED),
        expected_args={i.prompt: i.expected_args for i in suite.items if i.expected_args},
    )
    descriptor = provider.descriptor

    config = SweepConfig(
        catalogue=catalogue, suite=suite, factor_specs=FACTORS, repeats=REPEATS, seed=SEED
    )
    entries: dict[str, dict[str, object]] = {}
    for arm in build_arms(config):
        if arm.inert:
            continue
        for item in suite.items:
            for repeat in range(REPEATS):
                request = Request(prompt=item.prompt, catalogue=arm.catalogue, repeat_index=repeat)
                response = provider.complete(request)
                call = response.tool_call
                entries[request.key(descriptor)] = {
                    "text": response.text,
                    "tool_call": (
                        None
                        if call is None
                        else {"name": call.name, "arguments": dict(call.arguments)}
                    ),
                    "usage": dict(response.usage),
                }

    out = HERE / "cassette.json"
    write_cassette(
        out,
        descriptor=descriptor,
        entries=entries,
        provenance="synthetic",
        note=(
            "SYNTHETIC. Generated by toolsweep's deterministic MockProvider "
            "(examples/crm/make_cassette.py), not recorded from any language model. These "
            "responses say nothing about how any real model behaves. Regenerate with: "
            "python examples/crm/make_cassette.py"
        ),
    )
    size_kb = out.stat().st_size / 1024
    print(f"wrote {out} — {len(entries):,} entries, {size_kb:,.0f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
